name: my-docker-project

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: my-redis-container
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    image: my-app-image
    container_name: my-app-container
    command: /app/entrypoint.sh
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celery:
    image: my-app-image
    container_name: my-celery-container
    entrypoint: /app/celery_worker.sh
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - app

  beat:
    image: my-app-image
    container_name: my-beat-container
    entrypoint: /app/celery_beat.sh
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis
      - app

  nginx:
    build: ./nginx
    image: my-nginx-image
    container_name: my-nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
