services:
  django:
    build: .
    container_name: django_app
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    env_file: .env
    depends_on:
      - redis
      - django
    command: celery -A DCRCH worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: always
    env_file: .env
    depends_on:
      - redis
      - django
      - celery_worker
    command: celery -A DCRCH beat --loglevel=info

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  postgres_data:
