name: my-docker-project

services:
  app:
    build: .
    image: my-app-image
    container_name: my-app-container
    command: /app/entrypoint.sh
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jokes
      POSTGRES_USER: jokes
      POSTGRES_PASSWORD: jokes
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: my-redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: my-app-image
    container_name: my-celery-container
    entrypoint: /app/celery_worker.sh
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - app

  beat:
    image: my-app-image
    container_name: my-beat-container
    entrypoint: /app/celery_beat.sh
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - app

volumes:
  postgres_data:
  redis_data: